# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "dom-serializer-1.4.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.4.1.tgz";
        sha512 = "VHwB3KfrcOOkelEG2ZOfxqLZdfkil8PtJi4P8N2MMXucZq2yLp75ClViUlOVwyoHEDjYU433Aq+5zWP61+RGag==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-4.3.1" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.3.1.tgz";
        sha512 = "GrwoxYN+uWlzO8uhUXRl0P+kHE4GtVPfYzVLcUxPL7KNdHKj66vvlhiweIHqYYXWlw+T8iLMp42Lm67ghw4WMQ==";
      };
    };
    "domutils-2.8.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.8.0.tgz";
        sha512 = "w96Cjofp72M5IIhpjgobBimYEfoPjx1Vx0BSX9P30WBdZW2WIKU0T1Bd0kz2eNZ9ikjKgHbEyKx8BB6H1L3h3A==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "entities-3.0.1" = {
      name = "entities";
      packageName = "entities";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-3.0.1.tgz";
        sha512 = "WiyBqoomrwMdFG1e0kqvASYfnlb0lp8M5o5Fw2OFq1hNZxxcNk8Ik0Xm7LxzBhuidnZB/UtBqVCgUz3kBOP51Q==";
      };
    };
    "fclone-1.0.11" = {
      name = "fclone";
      packageName = "fclone";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fclone/-/fclone-1.0.11.tgz";
        sha512 = "GDqVQezKzRABdeqflsgMr7ktzgF9CyS+p2oe0jJqUY6izSSbhPIQJDpoU4PtGcD7VPM9xh/dVrTu6z1nwgmEGw==";
      };
    };
    "htmlparser2-7.2.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-7.2.0.tgz";
        sha512 = "H7MImA4MS6cw7nbyURtLPO1Tms7C5H602LRETv95z1MxO/7CP7rDVROehUYeYBUYEON94NXXDEPmZuq+hX4sog==";
      };
    };
    "is-json-2.0.1" = {
      name = "is-json";
      packageName = "is-json";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-json/-/is-json-2.0.1.tgz";
        sha512 = "6BEnpVn1rcf3ngfmViLM6vjUjGErbdrL4rwlv+u1NO1XO8kqT4YGL8+19Q+Z/bas8tY90BTWMk2+fW1g6hQjbA==";
      };
    };
    "posthtml-0.16.6" = {
      name = "posthtml";
      packageName = "posthtml";
      version = "0.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml/-/posthtml-0.16.6.tgz";
        sha512 = "JcEmHlyLK/o0uGAlj65vgg+7LIms0xKXe60lcDOTU7oVX/3LuEuLwrQpW3VJ7de5TaFKiW4kWkaIpJL42FEgxQ==";
      };
    };
    "posthtml-expressions-1.10.0" = {
      name = "posthtml-expressions";
      packageName = "posthtml-expressions";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-expressions/-/posthtml-expressions-1.10.0.tgz";
        sha512 = "c8njTjfqkDNhfx/ItK1N2D16Y2SNJ5fxH1+sOrP3FdMWiJxDBhDoR7gj3NU0jWFkbV+VSIn/asLcp9c8aI7WRQ==";
      };
    };
    "posthtml-include-1.7.4" = {
      name = "posthtml-include";
      packageName = "posthtml-include";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-include/-/posthtml-include-1.7.4.tgz";
        sha512 = "GO5QzHiM6/fXq8DxLoLN+jEW4sH/6nuGF9z+NJmP1qi1A3J2zCC7WwXrEwaPL3T8LrH+FL4IedK+mIJHbn5ZEA==";
      };
    };
    "posthtml-match-helper-1.0.3" = {
      name = "posthtml-match-helper";
      packageName = "posthtml-match-helper";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-match-helper/-/posthtml-match-helper-1.0.3.tgz";
        sha512 = "aeRAPvok2Fs6uzSm85665jdAk5UOd8US2QCkWtGU6yLPlKSwzWTSgZZuABc3UeNy3K1lVk/HV9bRkWJYN05Ymw==";
      };
    };
    "posthtml-parser-0.10.2" = {
      name = "posthtml-parser";
      packageName = "posthtml-parser";
      version = "0.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-parser/-/posthtml-parser-0.10.2.tgz";
        sha512 = "PId6zZ/2lyJi9LiKfe+i2xv57oEjJgWbsHGGANwos5AvdQp98i6AtamAl8gzSVFGfQ43Glb5D614cvZf012VKg==";
      };
    };
    "posthtml-parser-0.11.0" = {
      name = "posthtml-parser";
      packageName = "posthtml-parser";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-parser/-/posthtml-parser-0.11.0.tgz";
        sha512 = "QecJtfLekJbWVo/dMAA+OSwY79wpRmbqS5TeXvXSX+f0c6pW4/SE6inzZ2qkU7oAMCPqIDkZDvd/bQsSFUnKyw==";
      };
    };
    "posthtml-render-3.0.0" = {
      name = "posthtml-render";
      packageName = "posthtml-render";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/posthtml-render/-/posthtml-render-3.0.0.tgz";
        sha512 = "z+16RoxK3fUPgwaIgH9NGnK1HKY9XIDpydky5eQGgAFVXTCSezalv9U2jQuNV+Z9qV1fDWNzldcw4eK0SSbqKA==";
      };
    };
  };
  args = {
    name = "wimmelbild-study";
    packageName = "wimmelbild-study";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      (sources."dom-serializer-1.4.1" // {
        dependencies = [
          sources."entities-2.2.0"
        ];
      })
      sources."domelementtype-2.3.0"
      sources."domhandler-4.3.1"
      sources."domutils-2.8.0"
      sources."entities-3.0.1"
      sources."fclone-1.0.11"
      sources."htmlparser2-7.2.0"
      sources."is-json-2.0.1"
      sources."posthtml-0.16.6"
      (sources."posthtml-expressions-1.10.0" // {
        dependencies = [
          sources."posthtml-parser-0.10.2"
        ];
      })
      sources."posthtml-include-1.7.4"
      sources."posthtml-match-helper-1.0.3"
      sources."posthtml-parser-0.11.0"
      sources."posthtml-render-3.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
